[package]
name = "bpr"
version = "0.1.0"
authors = ["Lukas Geis <lukasgeis@gmx.de>"]
license = "MIT"
edition = "2018"

[dependencies]
structopt = { version = "0.3", default-features = false }
rand = "0.8.3"

[[bin]]
name = "bpr-file"
path = "src/bin/bpr-file.rs"
