name: tf_gene_networks

channels:
   - conda-forge
   - bioconda

dependencies:
  - meme==5.4.1
  - python==3.7.6
  - Requests==2.23.0
  - numpy==1.21.6
  - pybedtools==0.8.1
  - pandas==1.3.5
  - scipy==1.7.3